#include <stdlib.h>
#include <stdio.h>
#include "sem.h"

int bufferSize, in, out = 0;
int* buffer;

void prod(int tid, int runNum) {
    int i = 0;
    while (i < runNum) {
        P(&empty);
        i++;
        buffer[in] = tid;
        in = (in+1) % bufferSize;
        printf("\n Producer %d is producing item number %d \n", tid, i);
        V(&full);
        if (i == runNum){
            TCB_t* temp = DelQueue(&runQ);
            if (runQ == NULL) {
                exit(0);
            }
            swapcontext(&(temp->context), &(runQ->context));
        }
        else {
            yield();
        }
    }
}

void cons(int tid, int runNum) {
    int i = 0;
    while (i < runNum) {
        P(&full);
        i++;
        int prodNum = buffer[out];
        out = (out+1) % bufferSize;
        printf ("\n Consumer %d is consuming item generated by Producer %d \n", abs(tid), prodNum);
        V(&empty);
        if (i == runNum){
            TCB_t* temp = DelQueue(&runQ);
            if (runQ == NULL) {
                exit(0);
            }
            swapcontext(&(temp->context), &(runQ->context));
        }
        else {
            yield();
        }
    } 
}

int main(){
    int runNum, prodNum, consNum, tid = 0;
    scanf("%d,%d,%d,%d\n", &bufferSize, &prodNum, &consNum, &runNum);
    buffer = (int*)malloc(sizeof(int)* bufferSize);
    InitSem(&full, 0);
    InitSem(&empty, bufferSize);
    for (int i = 1; i <= prodNum+consNum; i++){
        scanf("%d\n", &tid);
        if (tid > 0){
            start_thread(prod, tid, runNum);
        }
        else {
            start_thread(cons, tid, runNum);
        }
    }
    run();
    return 0;
}